name: modal_bottom_sheet
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/modal_bottom_sheet.yaml"
      - "modal_bottom_sheet/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: modal_bottom_sheet
      min_coverage: 0 

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      working_directory: modal_bottom_sheet