name: sheet - web preview
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    defaults:
      run:
        working-directory: sheet/example
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v3

      - name: 🐦 Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true

      - name: 📦 Install Dependencies
        run: |
          flutter pub global activate very_good_cli
          very_good --analytics false
          very_good packages get --recursive

      - name: 🛠 Build web
        run: flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true

      - name: 🚀 Deploy to firebase hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHEET_PREVIEW }}'
          channelId: live
          projectId: sheet-preview
          entryPoint: sheet/example
