name: sheet
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/sheet.yaml"
      - "sheet/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      working_directory: sheet
      min_coverage: 75 # Working to reach 100% XD

  pana:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/pana.yml@v1
    with:
      working_directory: sheet